version: "3"
services:
    web:
        image: netcoreapp:latest
        depends_on:
            - "db"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
    db:
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
              - "1433:1433"
          environment:
              SA_PASSWORD: "Qwe123456"
              ACCEPT_EULA: "Y"